const fs = require('fs');
let c = fs.readFileSync('src/components/SettingsModule.tsx', 'utf8');

// Add Printer import
c = c.replace(
  "  LockKeyhole,\n  Unlock,\n  Calendar\n} from 'lucide-react';",
  "  LockKeyhole,\n  Unlock,\n  Calendar,\n  Printer\n} from 'lucide-react';"
);

// Add printEodReport function after playSound
const playSoundEnd = "oscillator.stop(audioContext.currentTime + 0.3);\n  };\n  \n  // Parameters form state copy";
const printFunc = "oscillator.stop(audioContext.currentTime + 0.3);\n  };\n  \n  const printEodReport = (report: EndOfDayReport) => {\n    const printWindow = window.open('', '_blank');\n    if (!printWindow) return;\n    const html = `\n      <!DOCTYPE html>\n      <html>\n      <head>\n        <title>End of Day Report - ${report.date}</title>\n        <style>\n          body { font-family: Arial, sans-serif; padding: 20px; }\n          .header { text-align: center; margin-bottom: 30px; }\n          .header h1 { margin: 0; color: #1e293b; }\n          .header p { margin: 5px 0; color: #64748b; }\n          table { width: 100%; border-collapse: collapse; margin-top: 20px; }\n          th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }\n          th { background: #f8fafc; font-weight: bold; }\n          .total-row { font-weight: bold; background: #fef2f2; }\n          .footer { margin-top: 30px; text-align: right; font-size: 12px; color: #64748b; }\n        </style>\n      </head>\n      <body>\n        <div class=\"header\">\n          <h1>NILE PREMIUM WATER</h1>\n          <p>End of Day Report</p>\n          <p>Date: ${report.date} | Generated: ${new Date(report.closedAt).toLocaleTimeString()}</p>\n        </div>\n        <table>\n          <tr><th>Metric</th><th>Value</th></tr>\n          <tr><td>Total Sales</td><td>${settings.currency}${report.totalSales.toLocaleString()}</td></tr>\n          <tr><td>Total Expenses</td><td>${settings.currency}${report.totalExpenses.toLocaleString()}</td></tr>\n          <tr><td>Production Bags</td><td>${report.totalProductionBags.toLocaleString()} bags</td></tr>\n          <tr><td>Nylon Used</td><td>${report.totalNylonUsed} kg</td></tr>\n          <tr><td>Closing Stock</td><td>${report.closingStock} bags</td></tr>\n          <tr class=\"total-row\"><td>Cash at Hand</td><td>${settings.currency}${report.cashAtHand.toLocaleString()}</td></tr>\n          <tr><td>Generated By</td><td>${report.generatedBy}</td></tr>\n        </table>\n        <div class=\"footer\">\n          <p>Printed on: ${new Date().toLocaleString()}</p>\n        </div>\n        <script>window.onload = () => { window.print(); }<\\/script>\n      </body>\n      </html>\n    `;\n    printWindow.document.write(html);\n    printWindow.document.close();\n  };\n  \n  // Parameters form state copy";

c = c.replace(playSoundEnd, printFunc);

fs.writeFileSync('src/components/SettingsModule.tsx', c);
console.log('Done');