const fs = require('fs');
let c = fs.readFileSync('src/components/SettingsModule.tsx', 'utf8');

// Add Printer column header
c = c.replace(
  "<th className=\"py-3.5 px-5 font-bold\">Generated By</th>\n                    </tr>",
  "<th className=\"py-3.5 px-5 font-bold\">Generated By</th>\n                      <th className=\"py-3.5 px-5 font-bold text-right\">Actions</th>\n                    </tr>"
);

// Add Print button after the Generated By cell
c = c.replace(
  "<td className=\"py-3.5 px-5 text-slate-300\">{report.generatedBy}</td>\n                      </tr>",
  "<td className=\"py-3.5 px-5 text-slate-300\">{report.generatedBy}</td>\n                        <td className=\"py-3.5 px-5 text-right\">\n                          <button\n                            onClick={() => printEodReport(report)}\n                            className=\"p-1.5 rounded-lg bg-slate-900 border border-slate-700 text-sky-400 hover:bg-sky-600 hover:text-white transition-all cursor-pointer\"
                            title=\"Print Report\"\n                          >\n                            <Printer className=\"w-3.5 h-3.5\" />\n                          </button>\n                        </td>\n                      </tr>"
);

fs.writeFileSync('src/components/SettingsModule.tsx', c);
console.log('Done');